---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jfrog
spec:
  interval: 24h
  url: https://cloudecho.github.io/charts/
  insecure: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory
spec:
  targetNamespace: artifactory
  storageNamespace: artifactory
  releaseName: artifactory
  interval: 40m
  timeout: 30m
  chart:
    spec:
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: jfrog
      interval: 12h
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
  valuesFrom:
    - kind: ConfigMap
      name: jfrog-values
      valuesKey: values.yaml
