apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory
spec:
  interval: 15m
  chart:
    spec:
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: jfrog
      interval: 12h
      version: "0.1.0"
  test:
    enable: false
  valuesFrom:
    - kind: ConfigMap
      name: jfrog-values
      valuesKey: values.yaml
