apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/apps
patches:
  - path: jfrog-values.yaml
    target:
      kind: HelmRelease
      name: artifactory

configMapGenerator:
  - name: jfrog-values
    namespace: staging
    files:
      - values.yaml=jfrog-staging-values.yaml

generatorOptions:
  disableNameSuffixHash: true
