apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/apps
patches:
  - path: jfrog-values.yaml
    target:
      kind: HelmRelease
      name: artifactory
  - path: promethues-metrics-staging.yaml
    target:
      kind: HelmRelease
      name: monitoring

configMapGenerator:
  - name: jfrog-values
    namespace: staging
    files:
      - values.yaml=promethues-staging-values.yaml
  - name: prometheus-values
    namespace: staging
    files:
      - values.yaml=promethues-staging-values.yaml

generatorOptions:
  disableNameSuffixHash: true
